apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: codeplanet1/micck8pat-auth
          env:
            - name: DB_CONNECTION
              value: "postgres"
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "auth"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DEFAULT_CLIENT
              value: "demo"
            - name: JWT_TOKEN_KEY
              value: "secrete"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
